spring:
  application:
    name: tasklet-batch

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/batch
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  h2:
    console:
      enabled: true

  batch:
    jdbc:
      initialize-schema: always
